### ISSUE TITLE
bug: CDK synth output is not valid CFN

### ISSUE THREAD

**Issue by fiserv-plat-eng** [cdklabs/cdk-validator-cfnguard#67]
Root issue: https://github.com/aws/aws-cdk/issues/25331

When using `CfnGuardValidator` with your CDK app

```typescript
const app = new App({policyValidationBeta1: [new CfnGuardValidator()],});
```

When generating cloudformation output

```bash
cdk synth  > template.yml
```

The generated cloudformation is no longer valid

```bash
cfn-lint template.yml
E0000 mapping values are not allowed in this context
template.yml:4:10
```

Add the produced yaml includes the following lines

```yaml
Performing Policy Validations

Policy Validation Successful!
Resources:
```

**Comment by corymhall** [comment]
@fiserv-plat-eng I'll close this issue since you created an issue in the `aws-cdk` repo.
